# Generated by Django 5.2.5 on 2025-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('address', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=13)),
                ('description', models.TextField(max_length=1500)),
                ('fb', models.URLField()),
                ('x_link', models.URLField()),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
