# Generated by Django 5.2.5 on 2025-08-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='fb',
            new_name='fb_link',
        ),
    ]
