# Generated by Django 5.2.5 on 2025-08-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='BaseAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('baseabout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.baseabout')),
            ],
            bases=('about.baseabout',),
        ),
        migrations.CreateModel(
            name='OurGoals',
            fields=[
                ('baseabout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.baseabout')),
            ],
            bases=('about.baseabout',),
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('baseabout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.baseabout')),
            ],
            bases=('about.baseabout',),
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('baseabout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.baseabout')),
            ],
            bases=('about.baseabout',),
        ),
    ]
