# Generated by Django 5.2.5 on 2025-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertybook_children_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
