# Generated by Django 5.2.5 on 2025-09-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_propertybook_children_alter_propertybook_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyReview',
        ),
    ]
